# Generated by Django 4.0.5 on 2022-06-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_Theme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='bg_color',
        ),
        migrations.AddField(
            model_name='theme',
            name='color1',
            field=models.CharField(default='#FFF', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='color2',
            field=models.CharField(default='#FFF', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='color3',
            field=models.CharField(default='#FFF', max_length=15),
            preserve_default=False,
        ),
    ]
