# Generated by Django 4.0.5 on 2022-06-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditPortfolio', '0002_heromodel_created_alter_heromodel_before_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
