# Generated by Django 4.0.5 on 2022-06-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditPortfolio', '0005_projectsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
