# Generated by Django 4.0.5 on 2022-06-14 16:31

from django.db import migrations, models
import django.utils.timezone
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('EditPortfolio', '0006_alter_projectsmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='title',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
