# Generated by Django 4.0.5 on 2022-06-14 16:47

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('EditPortfolio', '0007_projectsmodel_created_alter_projectsmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='full_description',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
